### ISSUE TITLE
Heading, bearing lines broken

### ISSUE THREAD

**Issue by RBerliner** [SignalK/freeboard-sk#30] opened 2017-08-04 21:15 UTC
The heading and bearing lines are broken for me as I do not yet use an electronic compass.

The code in freeboard-sk is a bit confusing and I don't know if it is wrong or if I don't understand it.

If the sentences navigation.headingTrue or navigation.headingMagnetic are never received, headingT and headingM are never calculated and the heading/bearing lines are not drawn.

The code uses an integer key, cog, to mark if the data is navigation.headingTrue (cog = 0), navigation.headingMagnetic (cog = 3), navigation.courseOverGroundMagnetic (cog = 2) or navigation.courseOverGroundTrue (cog = 1). 

The way the code is written, the data with the largest cog value is written to the displays.

I believe that all of these navigation sentences should result in the calculation of headingT and headingM.

**Comment by rob42** [comment] 2017-08-04 21:50
Hi Ron,

That whole process of choosing T or M headings is confusing. It never really worked as intended, and since one can be derived from the other, I'm not convinced a browser algo can ever choose the correct one automatically.

Im inclined to make it always use gps by default, and add compass by selecting in the config. At least that should be predictable. I guess the signalk-imu could be improved to send a recognizable flag to automate the config change, but maybe sort out a clean manually driven solution first?

Rob

August 5 2017 9:17 AM, "Ron Berliner"  wrote:
	The heading and bearing lines are broken for me as I do not yet use an electronic compass.

	The code in freeboard-sk is a bit confusing and I don't know if it is wrong or if I don't understand it.

	If the sentences navigation.headingTrue or navigation.headingMagnetic are never received, headingT and headingM are never calculated and the heading/bearing lines are not drawn.

	The code uses an integer key, cog, to mark if the data is navigation.headingTrue (cog = 0), navigation.headingMagnetic (cog = 3), navigation.courseOverGroundMagnetic (cog = 2) or navigation.courseOverGroundTrue (cog = 1).

	The way the code is written, the data with the largest cog value is written to the displays.

	I believe that all of these navigation sentences should result in the calculation of headingT and headingM.

**Comment by panaaj** [comment] 2018-10-12 23:59
#51 heading and bearing lines reflect received values `headingMagnetic` or `headingTrue` based on the selection made in `settings` screen.

**Comment by panaaj** [comment] 2018-10-15 22:09
#51 is the basis of v1.0.0 release.  Will  close this issue, a new issue can be raised if it is deemed to be unresolved.

**Closed by panaaj** 2018-10-15 22:09 UTC
Labels: legacy
