### ISSUE TITLE
Weather not downloaded

### ISSUE THREAD

**Issue by dirkwa** [SignalK/freeboard-sk#196] opened 2024-10-22 22:23 UTC
I am running SK 2.11.0 with Freeboard-SK 2,11,5
I have configured the API Key in Server/Plugins.

![image](https://github.com/user-attachments/assets/e1ab7947-d223-4c0c-bfdb-e1f9839bf0d3)

The error I see on the dashboard is:
![image](https://github.com/user-attachments/assets/ebd7ba40-d6e1-4e55-ae3e-d850d8cbc834)

Any Idea what I missed?

**Comment by dirkwa** [comment] 2024-10-22 23:11
In the SK Server log I see:
Oct 23 11:08:20 2024-10-22T23:08:20.335Z @signalk/freeboard-sk *** Weather: wake from sleep....poll provider.
Oct 23 11:08:20 2024-10-22T23:08:20.335Z @signalk/freeboard-sk Wake timer watchdog -> OK
Oct 23 11:08:20 2024-10-22T23:08:20.335Z @signalk/freeboard-sk *** Weather: Polling provider.
Oct 23 11:08:20 2024-10-22T23:08:20.335Z @signalk/freeboard-sk *** Vessel position: {"longitude":177.1840683,"latitude":-17.774065}.
Oct 23 11:08:20 2024-10-22T23:08:20.335Z @signalk/freeboard-sk *** Weather: Next poll due in 56 min(s)... sleep for 60 secs...

**Comment by dirkwa** [comment] 2024-10-22 23:12
![image](https://github.com/user-attachments/assets/0f88e8f0-1244-4c0d-af7f-706beee93d7e)

**Comment by panaaj** [comment] 2024-10-23 02:36
This error indicates that the interval timer has "runaway" and the watchdog mechanism has kicked in and halted it.
This by design and protects from costs being incurred for exceeding API call limits.
If debug is turned on for the plugin you would see that the timestamps show that the timer is not sleeping for 60 secs.

From experience the resolution is to reboot the rpi device as the issue is relating to the  underlying OS services exposed to the plugin via nodejs.

**Comment by dirkwa** [comment] 2024-10-23 03:28
Hmm. I rebooted the RPI and enabled the debug log. The log says:

Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** initAlarms() **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering Alarm Action Handler(s) **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering mob Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering fire Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering sinking Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering flooding Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering collision Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering grounding Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering listing Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering adrift Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering piracy Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering abandon Handler **
Oct 23 15:24:42 2024-10-23T03:24:42.081Z @signalk/freeboard-sk ** Registering Alarm Action API endpoint(s) **
Oct 23 15:24:42 2024-10-23T03:24:42.082Z @signalk/freeboard-sk *** Weather: settings: {"enable":true,"apiVersion":3,"apiKey":"e885b691e4c82637fa1abc9240553cf2","pollInterval":60}
Oct 23 15:24:42 2024-10-23T03:24:42.082Z @signalk/freeboard-sk *** fetchInterval: 3600000
Oct 23 15:24:42 2024-10-23T03:24:42.082Z @signalk/freeboard-sk *** Vessel position: {"longitude":177.1840346,"latitude":-17.7748155}.
Oct 23 15:24:42 2024-10-23T03:24:42.082Z @signalk/freeboard-sk *** Weather: Calling service API.....(attempt: 1)
Oct 23 15:24:42 2024-10-23T03:24:42.082Z @signalk/freeboard-sk Position: {"longitude":177.1840346,"latitude":-17.7748155}
Oct 23 15:24:42 2024-10-23T03:24:42.082Z @signalk/freeboard-sk *** Weather: polling weather provider.
Oct 23 15:24:42 ::ffff:192.168.0.150 - - [23/Oct/2024:03:24:42 +0000] "POST /skServer/plugins/freeboard-sk/config HTTP/1.1" 200 45 "http://192.168.0.10:3000/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0"
Oct 23 15:24:42 2024-10-23T03:24:42.820Z @signalk/freeboard-sk *** Weather: data received....
Oct 23 15:24:42 2024-10-23T03:24:42.820Z @signalk/freeboard-sk **** METEO - emit deltas*****
Oct 23 15:24:42 2024-10-23T03:24:42.820Z @signalk/freeboard-sk **** METEO *****
Oct 23 15:24:42 2024-10-23T03:24:42.820Z @signalk/freeboard-sk **** METEO OBS *****

But there is no weather data avialable in FreeboardSK....

**Comment by panaaj** [comment] 2024-10-23 04:07
The weather data should be visible in the data browser in the server admin UI under the metro.freeboard context

**Comment by dirkwa** [comment] 2024-10-23 04:16
Sadly it is not. Do I need a influxdb connected to store that data?

![image](https://github.com/user-attachments/assets/0b304f86-4100-4fd6-95ff-5445bfe45119)

**Comment by panaaj** [comment] 2024-10-23 05:32
Can you change the context to `meteo.freeboard-sk`?

Does it appear in the drop down?

**Comment by dirkwa** [comment] 2024-10-23 12:31
wget https://api.openweathermap.org/data/3.0/onecall?lat=$-17.77435&lon=$177.1838333&exclude=minutely,daily&appid=$e885b691e4c82637fa1abc9240553cf2

RESULT
--2024-10-24 00:25:09--  https://api.openweathermap.org/data/3.0/onecall?lat=himBHs17.77435
Resolving api.openweathermap.org (api.openweathermap.org)... 38.89.70.155
Connecting to api.openweathermap.org (api.openweathermap.org)|38.89.70.155|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
****
#############################################
dirk@pi5:~ $ curl https://api.openweathermap.org/data/3.0/onecall?lat=$-17.77435&lon=$177.1838333&exclude=minutely,daily&appid=$e885b691e4c82637fa1abc9240553cf2
[1] 3831
[2] 3832
[3] 3833
[2]-  Done                    lon=$177.1838333
dirk@pi5:~ $ {"cod":401, "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."}

![image](https://github.com/user-attachments/assets/e5ecc0ee-7c3e-4cd6-b675-d30fe759003c)

**Comment by dirkwa** [comment] 2024-10-23 12:52
Nope, looking into your code I founf the API URL and when I curl it I get:


 {"cod":401, "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."}

I was expecting that this here is good enough:
![image](https://github.com/user-attachments/assets/669d2918-9283-40d7-8790-943e3c941b5d)

Now I saw that I have to put my CreditCard maybe. Did this and now I am waiting that they activate the key for me.

A SK log entry of the above would have been super helpful, the dashboard does not really indicate that there is an issue.
![image](https://github.com/user-attachments/assets/8a83b9c3-9efa-4324-9af6-7a31d8ee8db7)

**Comment by panaaj** [comment] 2024-10-24 01:44
Will update to show error details in dashboard.

**Comment by panaaj** [comment] 2024-10-24 05:48
fixed in v2.12.0 release

**Closed by panaaj** 2024-10-24 05:48 UTC
