### ISSUE TITLE
Using the freeboard with mobile device is quite difficult

### ISSUE THREAD

**Issue by heikkimu** [SignalK/freeboard-sk#98] opened 2021-08-03 14:44 UTC
- disable text selection
- disable pinch zooming of the html-elements, not map
- add a short delay for the touch-event, when creating a route

**Comment by heikkimu** [comment] 2021-08-03 14:45
I could create a pr with the fixes.

**Comment by panaaj** [comment] 2021-08-04 05:02
Have added mobile specific viewport and style attributes to address the issues you mentioned to next realease (v1.17.0).
FYI v1.17.0 will use "singleClick" instead of "click" event which intriduces the delay for touch events.

**Comment by panaaj** [comment] 2021-08-04 05:04
closed by [ac73fc4](https://github.com/SignalK/freeboard-sk/commit/ac73fc4f05904a2edf8a63c946b5c78005578df0)

**Comment by heikkimu** [comment] 2021-08-07 09:13
Thanks @panaaj .

Unfortunately https://github.com/SignalK/freeboard-sk/commit/ac73fc4f05904a2edf8a63c946b5c78005578df0 won't quite cut it. IOS is neglecting the viewport-locks. I tested out the viewport & css-solutions but they did not work. 

I got this solution to work, but I think I'd add some more safe guards on it: https://github.com/SignalK/freeboard-sk/pull/100/commits/573151b3e041d689a4634da98960be83dc801da3

There are also a bit lighter styles for help-component:
https://github.com/SignalK/freeboard-sk/pull/100/commits/31512396c85b55633943ef6451f22c6f93bc9414

I couldn't get the project compiling in dev-mode without adding:
```
diff --git a/tsconfig.json b/tsconfig.json
index 37f57cf2..73d2ffdb 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -12,6 +12,7 @@
     "moduleResolution": "node",
     "importHelpers": true,
     "target": "es2015",
+    "skipLibCheck": true,
     "typeRoots": [
       "node_modules/@types"
     ],
```

**Comment by heikkimu** [comment] 2021-08-07 09:18
I was also thinking to experiment with https://github.com/richtr/NoSleep.js, which disables the screen sleep, so I don't need to mess with the phone's power options. I could try to make it configurable.

**Comment by tkurki** [comment] 2021-08-07 10:47
Nosleep is interesting! Would it make sense to have it configurable per webapp, including admin with embedded apps, or globally?

**Comment by heikkimu** [comment] 2021-08-07 14:39
@tkurki I’m rather new in this project, so I was thinking it to be configurable in same manner than the settings of Freeboard-sk.

Layout-wise we also have a lot of room. We’d use the same conventiins than other marine-navigation apps, which makes the adaptation easier for new users.

Do you have a discord-server / some other means for communication?

**Comment by panaaj** [comment] 2021-08-08 10:25
> I was also thinking to experiment with https://github.com/richtr/NoSleep.js, which disables the screen sleep, so I don't need to mess with the phone's power options. I could try to make it configurable.

The wakeLock feature is only available to Android devices at this time.
https://developer.mozilla.org/en-US/docs/Web/API/WakeLock

**Comment by tkurki** [comment] 2021-08-09 06:00
@heikkimu http://signalk.org/ => Slack

**Comment by panaaj** [comment] 2021-08-11 02:10
> Unfortunately [ac73fc4](https://github.com/SignalK/freeboard-sk/commit/ac73fc4f05904a2edf8a63c946b5c78005578df0) won't quite cut it. IOS is neglecting the viewport-locks. I tested out the viewport & css-solutions but they did not work.

It seems that the zooming is by design (regardless of the viewport attributes) as Apple do not want to inhibit accessibilty features for those who require it. Using (my old IOS 12) iPad confirms this.
Also I have noticed on this older IOS version Openlayers touch gestures do not work (you need to enable the `Pointer Events`  in Settings | Safari | Advanced | Experimental Features)

All settings work as expected on my Android device.

**Closed** 2021-08-11 04:51 UTC
