### ISSUE TITLE
Questions on usage

### ISSUE THREAD

**Issue by stevepmitchell** [SignalK/freeboard-sk#2] opened 2016-06-03 05:41 UTC
I had a few questions on installation and using freeboard-sk:

I have signalk-server-node already running on my system. Can I use that instead?
Can I run freeboard-sk on my linux machine, or does it have to be on Windows?
I've gotten through npm install and npm start, but what port is it listening on?

Thanks!

**Comment by rob42** [comment] 2016-06-03 20:58
Hi Steve,
Freeboard-SK Is just an html5 app. I just needs to go onto any web server,so alongside instrument-panel or sailguage is fine. Away sailing for a few days so answers may be slow
Rob.

<div>-------- Original message --------</div><div>From: Steve Mitchell <notifications@github.com> </div><div>Date:03/06/2016  17:41  (GMT+12:00) </div><div>To: SignalK/freeboard-sk <freeboard-sk@noreply.github.com> </div><div>Subject: [SignalK/freeboard-sk] Questions on usage (#2) </div><div>
</div>I had a few questions on installation and using freeboard-sk:

I have signalk-server-node already running on my system. Can I use that instead?
Can I run freeboard-sk on my linux machine, or does it have to be on Windows?
I've gotten through npm install and npm start, but what port is it listening on?

Thanks!

**Comment by stevepmitchell** [comment] 2016-06-03 22:49
No worries on the slow replies.

Ok so I have it in a web directory, it loads a map and such, but how would
I configure it to use my SignalK server?  I poked around for config files
or something else in terms of an IP and port to point it to, but couldn't
find it.

Steve Mitchell - Editor, SailBits.com <https://www.SailBits.com> |
steve@sailbits.com | 206-659-6911
Member, Boating Writers International <http://www.bwi.org>

**Comment by rob42** [comment] 2016-06-03 23:22
It might still be hardcoded to local host'-3000- i-ts still a work in progress -feel free to add a pull request.

<div>-------- Original message --------</div><div>From: Steve Mitchell <notifications@github.com> </div><div>Date:04/06/2016  10:49  (GMT+12:00) </div><div>To: SignalK/freeboard-sk <freeboard-sk@noreply.github.com> </div><div>Cc: rob42 <robert@42.co.nz>, Comment <comment@noreply.github.com> </div><div>Subject: Re: [SignalK/freeboard-sk] Questions on usage (#2) </div><div>
</div>No worries on the slow replies.

Ok so I have it in a web directory, it loads a map and such, but how would
I configure it to use my SignalK server? I poked around for config files
or something else in terms of an IP and port to point it to, but couldn't
find it.

Steve Mitchell - Editor, SailBits.com <https://www.SailBits.com> |
steve@sailbits.com | 206-659-6911
Member, Boating Writers International <http://www.bwi.org>

**Comment by rob42** [comment] 2016-06-10 05:37
Just pushed an update that should be better, pls try that. There were a number of problems with drawing the vessel.  It gets the signalk ws addresses from http://.../signalk/endpoints/v1 as a REST json doc, then uses the info to find the ws host/port

**Comment by rob42** [comment] 2016-06-10 05:48
Incidentally charts currently have to be manually installed in ../mapcache/'+title+'/' + z + '/' + x + '/' + y + '.png'.  Using the signalk maptools project this will eventually be automated (I hope!).

Meanwhile the freeboard-installer project can make the correct directory structure for you.
https://github.com/rob42/freeboard-installer.

Then edit lib/addLayers.js manually, as per the examples in the file. I need to do a proper guide, but time is short...

**Comment by stevepmitchell** [comment] 2016-06-10 16:14
Pulled down the newest update, but I still never see it attempt to connect
to my SignalK server.

Steve Mitchell - Editor, SailBits.com <https://www.SailBits.com> |
steve@sailbits.com | 206-659-6911
Member, Boating Writers International <http://www.bwi.org>

**Comment by rob42** [comment] 2016-06-10 22:35
Need some debug. Can you paste the output of http://..../signalk for you signalk server pls?
Also load  freeboard-sk and paste the browser console output.

**Comment by stevepmitchell** [comment] 2016-06-10 23:25
No worries, just trying to help!

Here's the output of my signalk server:

{"endpoints":{"v1":{"version":"1.alpha1","signalk-http":"http://grace:3000/signalk/v1/api/","signalk-ws":"http://grace:3000/signalk/v1/stream"}}}

It appears there's still some port/hostname confusion.  It's
requesting http://grace/signalk and getting a 404 (note the missing
port number).  So I added a proxy to my front-end lighttpd server to
catch anything /signalk/ and send to port 3000, and that fails with an
error about using web sockets versus HTTP.  Both errors are below.

I suspect the second error is an artifact of attempting to use a proxy
in lighttpd to pass through to the SignalK server.

[image: Inline image 1]

[image: Inline image 2]


Steve Mitchell - Editor, SailBits.com <https://www.SailBits.com> |
steve@sailbits.com | 206-659-6911
Member, Boating Writers International <http://www.bwi.org>

**Comment by rob42** [comment] 2016-06-11 01:30
The problem is in the url/webserver setup. The initial attempt to get /signalk will try the same server:port where the browser loaded the freeboard-sk/index.html page. So that look like http://grace/freeboard-sk/index.html, which looks for the REST interface on http://grace/signalk. This works for me as the signalk server is the same server as the signalk REST server. 
If you are serving pages from http://server1, and signalk REST url server is not on the same server or the root /signalk url then you will get the effect you see. 

There is also a difference between REST (http://) and the websockets (ws://). Some implementations run them on the same port and 'upgrade' when using 'ws://'. For technical reasons my java server runs them on separate ports, so I see the same error as you if I go to http://localhost:3000, as that only serves ws://. My REST interface is on localhost:8080. I think you are seeing the same effect.

Its going to be difficult to proxy the two ports as the resources have the same base path. You may need to setup differently

**Comment by stevepmitchell** [comment] 2016-06-11 02:57
I would imagine many people would set things up this way.  I have been
running the signalk-server-node for a long time as a standalone directory,
checked out via git, updated every week or so, and running as a standalone
node app on port 3000, which is the default.

I have another standalone webserver for random static content, including
freeboard-sk.

Any suggestions on how someone would set this up would be appreciated.

Steve Mitchell - Editor, SailBits.com <https://www.SailBits.com> |
steve@sailbits.com | 206-659-6911
Member, Boating Writers International <http://www.bwi.org>

**Comment by tkurki** [comment] 2016-06-11 06:30
It sounds like Steve has successfully proxied /signalk to serve the endpoints doc, whose content is not changed by proxying and both REST and ws will point to port 3000. 

After that it looks like freeboard does not honor the port but tries to connect to 80 and lighthttpd does not support proxying ws.

Freeboard should support bootstrapping the connections given a single /signalk doc.

Steve: you can try serving freeboard with the node server, just place it under bower_components, like instrumentpanel etc. 

I won't be able to offer much assistance for another week or so.

PS email inline images do not work in GH, use the web interface for that.

**Comment by stevepmitchell** [comment] 2016-06-11 17:01
Thanks, forgot this was GH, will post images in the web interface in the
future.

Moved freeboard-sk under bower_components and things are getting further,
but still getting the websockets error.

Steve Mitchell - Editor, SailBits.com <https://www.SailBits.com> |
steve@sailbits.com | 206-659-6911
Member, Boating Writers International <http://www.bwi.org>

**Comment by tkurki** [comment] 2016-06-16 16:48
The problem here is that freeboard handles only ws:// urls and current node server `/signalk` response ws endpoint has an http:// url.

We need to either change freeboard to accept http:// urls (signalk-js-client handles both) or node server to hand out ws:// urls.

And specify this in more detail in the spec and add a test for this in the testclient.

**Comment by ph1l** [comment] 2017-03-11 04:28
I'm running signalk-server-node and want to try out SignalK/freeboard-sk, do I just symlink to the freeboard checkout from somewhere in signalk-server-node/?

or do I do this:

    pi@freeboard:~/signalk-server-node $ npm install https://github.com/SignalK/freeboard-sk.git

?

doesn't seem to show up in /apps when i tried npm install from the signalk-server-node dir.. Maybe I'm confused as to how node works? I am a node n00b.

Thanks!

**Comment by tkurki** [comment] 2017-03-11 07:36
https://github.com/SignalK/signalk-server-node/pull/160 is not yet merged, so npm installed webapps are not yet supported in node server and freeboard-sk is not yet marked by the `signalk-webapp` keyword in package.json.

Node server mounts some file system directories under http root, mainly `bower_components` and `public`. Try placing it under `bower_components` and see if it works. The issue mentioned above about http/ws protocols in `/signalk` response is resolved afaik.

**Comment by panaaj** [comment] 2018-10-12 23:55
#51 honours the endpoints provided in `/signalk` response for both http and ws.
Freeboard still expects to be hosted on the signal k server and will query `/signalk` at the hostname in the browser URL.

Not sure if this closes this issue.. if not it sounds like a feature request.

**Comment by panaaj** [comment] 2018-10-15 22:19
Closing this issue on release of v1.0.0. Can be re-opened if deemed not to be resolved.

**Closed by panaaj** 2018-10-15 22:19 UTC
Labels: legacy
